### PR TITLE
Updated as much as I can to 1.19.3

### PR DESCRIPTION
**Pull request by TechPro424**
Updated as much as I can to 1.19.3, there are a lot of errors though, so you probably need to use a separate branch to avoid messing up main if you decide to accept the PR

### CODE REVIEW

**Review by TechPro424 — COMMENTED** [review]
There are still some methods that I cannot seem to find so I left them in ProfileKeysImplMixin for the time being

**Comment by TechPro424** [comment]
And remember to migrate your mappings to "1.19.3+build.5", just a note as I forget to do that most times and thought it might be useful for you too

**Comment by TechPro424** [comment]
Both the signChatMessage and signArguments methods in the ClientPlayerEntity class do not exist in 1.19.3, fyi

**Comment by Daxanius** [comment]
Great work! I had an update sitting ready on my computer, but I ran into a weird issue with it not compiling correctly. I'll check this out

**Comment by Daxanius** [comment]
> There are still some methods that I cannot seem to find so I left them in ProfileKeysImplMixin for the time being

If I recall correctly, the way messages are signed was changed significantly. Some methods aren't present in the new ProfileKeysImpl class, I resolved that in my local changes to just modify the public methods.

**Comment by Daxanius** [comment]
After reinstalling java and migrating mappings, the build for your changes seems to be failing on my end. I've tried a lot, even on my local changes and not much seems to change. I'm just gonna wait for me to go to my mom next week to try on my desktop there and hope for the best. I've had my fair share of getting frustrated at Java for being the pain in the butt that it is.

**Comment by TechPro424** [comment]
My PR still has a lot of errors so the build failing isn't surprising

**Comment by TechPro424** [comment]
Have you tried on your desktop? (Just asking for an update, it's fine if you haven't)

**Comment by Daxanius** [comment]
Appreciate the work! It ended up helping me track the issue and fix it. Though your changes themselves are not included in the new release.

**Pull request closed without merging**
