### PR TITLE
update to 1.20.2

### LINKED ISSUE #30: Update to 1.20

### PR DESCRIPTION
**Pull request by TechPro424**
This PR updates the mod to 1.20.2
Fixes #30 

I know my forked repo name says 1.19.3 but the PR is to update to 1.20.2

### CODE REVIEW

**Comment by TechPro424** [comment]
Bump

**Comment by TechPro424** [comment]
Bump

**Comment by Daxanius** [comment]
Thanks for your hard work! Checked it out and it seems to be working fine.

I'll put the release on Modrinth and add you as a Project member.

I apologize for my late reply, I've been very busy with life lately.

**Comment by TechPro424** [comment]
No problem, life can get quite hectic sometimes!
Thanks for the invite!

**Pull request merged**
